@TheBigStore.WebAPI_HostAddress = https://localhost:7165


GET {{TheBigStore.WebAPI_HostAddress}}/api/user?UserId=1

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/users?apikey=12345

###

POST {{TheBigStore.WebAPI_HostAddress}}/api/user/create
Content-Type: application/json

{
  "userName": "Jens",
  "password": "Pass",
  "email": "Jens@Jensen.dk",
  "roleId": 3
}

###

DELETE {{TheBigStore.WebAPI_HostAddress}}/api/user/remove?UserId=2

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/users/GetDeffered

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/categories

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/category?CategoryId=1

###

POST {{TheBigStore.WebAPI_HostAddress}}/api/category/create
Content-Type: application/json

{
  //CategoryDto
}

###

PUT {{TheBigStore.WebAPI_HostAddress}}/api/category/edit
Content-Type: application/json

{
  //CategoryDto
}

###

DELETE {{TheBigStore.WebAPI_HostAddress}}/api/category/remove?CategoryId=1

###

PATCH {{TheBigStore.WebAPI_HostAddress}}/api/category/update?CategoryId=1
Content-Type: application/json

{
  //JsonPatchDocument
}

###

POST {{TheBigStore.WebAPI_HostAddress}}/api/order
Content-Type: application/json

{
  //OrderDto
}

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/product?id=1

###

POST {{TheBigStore.WebAPI_HostAddress}}/api/product/create
Content-Type: application/json

{
  //ItemDto
}

###

PUT {{TheBigStore.WebAPI_HostAddress}}/api/product/edit
Content-Type: application/json

{
  //ItemDto
}

###

DELETE {{TheBigStore.WebAPI_HostAddress}}/api/product/remove?id=1

###

PATCH {{TheBigStore.WebAPI_HostAddress}}/api/product/update?id=1
Content-Type: application/json

{
  //JsonPatchDocument
}

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/products?page=1&count=10

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/products/search/string

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/role?RoleId=0

###

POST {{TheBigStore.WebAPI_HostAddress}}/api/role/create
Content-Type: application/json

{
  //RoleDto
}

###

PUT {{TheBigStore.WebAPI_HostAddress}}/api/role/edit
Content-Type: application/json

{
  //RoleDto
}

###

DELETE {{TheBigStore.WebAPI_HostAddress}}/api/role/remove?RoleId=1

###

PATCH {{TheBigStore.WebAPI_HostAddress}}/api/role/update?RoleId=1
Content-Type: application/json

{
  //JsonPatchDocument
}

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/user?UserId=1

###

PUT {{TheBigStore.WebAPI_HostAddress}}/api/user/edit
Content-Type: application/json

{
  //UserDto
}

###

DELETE {{TheBigStore.WebAPI_HostAddress}}/api/user/remove?UserId=1

###

PATCH {{TheBigStore.WebAPI_HostAddress}}/api/user/update?UserId=1
Content-Type: application/json

{
  //JsonPatchDocument
}

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/users

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/roles

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/orders

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/users

###

POST {{TheBigStore.WebAPI_HostAddress}}/api/user/create
Content-Type: application/json

{
  //UserDto
      
    "userName": "admin",
    "password": "admin",
    "email": "admin@thebigstore.com",
    "roleId": 1,
    "customerId": null,
  
}

###

POST {{TheBigStore.WebAPI_HostAddress}}/item/create
Content-Type: application/json

{
  "itemName": "Ender 3 Pro",
  "description": "A good cheap 3D Printer",
  "price": 1700.0,
  "categoryId": 1,
}
