@TheBigStore.WebAPI_HostAddress = https://localhost:7165


GET {{TheBigStore.WebAPI_HostAddress}}/api/user?UserId=1

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/users?apikey=12345

###

POST {{TheBigStore.WebAPI_HostAddress}}/api/user/create
Content-Type: application/json

{
  "userName": "Jens",
  "password": "Pass",
  "email": "Jens@Jensen.dk",
  "roleId": 3
}

###

DELETE {{TheBigStore.WebAPI_HostAddress}}/api/user/remove?UserId=2

###

GET {{TheBigStore.WebAPI_HostAddress}}/api/users/GetDeffered

###